### ISSUE TITLE
עדכן את האתר לקראת ההשקה

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#185]
מה צריך לעשות - 

- [x] להסיר את הכותרת "בהרצה" 
- [x] לסיים את גרפים מגמות - #171 
- [x] הצג את הגרפים ב- #170 ו- #169
- [x] לסיים את משימה #177

**Comment by morchickit** [comment]
יוני ביקש גם שנכניס שהאתר מעודכן לשנת 2021. 
אפשר להוסיף לפני השורה הזו האחרונה של "מידע נוסף" את המשפט הבא - "המידע באתר מעודכן לשנת 2021. המידע לשנת 2022 יעודכן במהלך שנת 2023".

**Comment by morchickit** [comment]
אדם, שים לב להערה שלי משבוע שעבר על שנת עדכון האתר. פותחת.
